### ISSUE TITLE
fail gracefully on bad geoms

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/sharedstreets-conflator#9]
Getting the following error on two shapefiles (DC and Chicago centerline data):

<img width="1019" alt="screen shot 2018-02-20 at 2 52 54 pm" src="https://user-images.githubusercontent.com/43052/36446006-ebeb9658-164d-11e8-9bc3-b3a50cd5d1f9.png">

(note the progress bars! ⏱️📈)

**Comment by DenisCarriere** [comment]
👍 fails very gracefully 😄 

I'll look into this, I don't think my closed loop patch got published yet.

**Comment by DenisCarriere** [comment]
Possible other issues with Shapefiles:
- [ ] Entries might have geometry as "`null`"
- [ ] Mixed LineString & MultiLineString

**Comment by kpwebb** [comment]
ah ok! i was thinking this might require a try/catch on the loop processing the geoms to deal with weird edge cases

**Comment by DenisCarriere** [comment]
> note the progress bars! 

I can add that too 🤓 (upcoming)

**Comment by DenisCarriere** [comment]
> weird edge cases

Lots of "silly" things with Shapefiles, just need to hammer out the known errors, afterwards we can try/catch the rest.

**Comment by DenisCarriere** [comment]
The great thing with the Shapefile library is it converts the data into GeoJSON, so I can just need to handle some of the known GeoJSON edge cases.

**Comment by kpwebb** [comment]
@DenisCarriere here are the two Shapefiles that trigger this (fails for both around 75% mark):

dc:
https://www.dropbox.com/s/sngegulqc90fffm/dc_street_centerlines.zip?dl=0

chicago:
https://www.dropbox.com/s/e8qpw07u2gt0oxl/chicago_street_center_lines.zip?dl=0

**Comment by DenisCarriere** [comment]
👍 Thanks, was going to ask for those

**Comment by DenisCarriere** [comment]
🤔 We might need to stream the data out into a JSONL (JSON Line), the Chicago Shapefile is 403MB.

Let me see, I've got the Toronto one to work so far.. 🤔

Chicago:

```
$ ./bin/sharedstreets-conflator.js test/in/chicago_street_center_lines.shp
TypeError: Cannot read property '0' of undefined
    at pointToTileFraction (/Users/mac/Github/sharedstreets-conflator/node_modules/global-mercator/global-m
ercator.js:64:29)
    at Object.pointToTile (/Users/mac/Github/sharedstreets-conflator/node_modules/global-mercator/global-me
rcator.js:42:14)
    at geometry (/Users/mac/Github/sharedstreets-conflator/index.js:85:28)
    at geometry.next (<anonymous>)
    at Object.conflator (/Users/mac/Github/sharedstreets-conflator/index.js:46:20)
    at conflator.next (<anonymous>)
    at /Users/mac/Github/sharedstreets-conflator/bin/sharedstreets-conflator.js:70:20
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mac/Github/sharedstreets-conflator/bin/sharedstreets-conflator.js:5:58)
    at <anonymous>
```

DC:

```
$ ./bin/sharedstreets-conflator.js test/in/dc_street_centerlines.shp -o ./data
Error: coordinates must contain numbers
    at Object.lineString (/Users/mac/Github/sharedstreets-conflator/node_modules/@turf/helpers/index.js:299:77)
    at outboundBearing (/Users/mac/Github/sharedstreets-conflator/node_modules/sharedstreets/index.js:407:51)
    at Object.geometry (/Users/mac/Github/sharedstreets-conflator/node_modules/sharedstreets/index.js:87:22)
    at geometry (/Users/mac/Github/sharedstreets-conflator/index.js:86:33)
    at geometry.next (<anonymous>)
    at Object.conflator (/Users/mac/Github/sharedstreets-conflator/index.js:46:20)
    at conflator.next (<anonymous>)
    at /Users/mac/Github/sharedstreets-conflator/bin/sharedstreets-conflator.js:70:20
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mac/Github/sharedstreets-conflator/bin/sharedstreets-conflator.js:5:58)
```

**Comment by DenisCarriere** [comment]
> note the progress bars!

👍I like it

**Comment by DenisCarriere** [comment]
I'll add a try/catch exception for now until we can pinpoint the issue.

**Comment by DenisCarriere** [comment]
Should be working now, both Chicago & DC only have 1 skipped geometry... 🤔 will investigate more why, closing for now and open a new issue/PR.
